import Head from "next/head";
import { createClient } from "contentful";
import JobCard from "../components/jobcard/JobCard";
import Container from "../components/container/Container";
export async function getServerSideProps() {
  const client = createClient({
    space: process.env.CONTENT_SPACE_ID,
    accessToken: process.env.CONTENT_ACCESS_TOKEN,
  });
  const res = await client.getEntries({ content_type: "jobTitle" });

  return { props: { jobs: res.items } };
}

const Home = ({ jobs })=> {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        {jobs.map((job) => (
          <JobCard key={job.sys.id} job={job} />
        ))}
      </Container>
    </>
  );
}


Home.layout = "MainLayout";
export default Home