import Head from "next/head";
import { createClient } from "contentful";
export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENT_SPACE_ID,
    accessToken: process.env.CONTENT_ACCESS_TOKEN,
  });
  const res = await client.getEntries({ content_type: "jobTitle" });

  return { props: { jobs: res.items } };
}

export default function Home({ jobs }) {
  console.log(jobs);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {jobs.map((job) => job.fields.jobTitle)}
    </>
  );
}
